export const LOGOUT = 'LOGOUT';

export const LOGIN_OR_REGISTER_PENDING = 'LOGIN_OR_REGISTER_PENDING';
export const LOGIN_OR_REGISTER_SUCCESS = 'LOGIN_OR_REGISTER_SUCCESS';
export const LOGIN_OR_REGISTER_FAILED = 'LOGIN_OR_REGISTER_FAILED';

export const RESET_PASSWORD_PENDING = 'RESET_PASSWORD_PENDING';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const ADD_RECORD_PENDING = 'ADD_RECORD_PENDING';
export const ADD_RECORD_SUCCESS = 'ADD_RECORD_SUCCESS';
export const ADD_RECORD_FAILED = 'ADD_RECORD_FAILED';

export const GET_RECORDS_FROM_USER_PENDING = 'GET_RECORDS_FROM_USER_PENDING';
export const GET_RECORDS_FROM_USER_SUCCESS = 'GET_RECORDS_FROM_USER_SUCCESS';
export const GET_RECORDS_FROM_USER_FAILED = 'GET_RECORDS_FROM_USER_FAILED';

export const DELETE_RECORD_PENDING = 'DELETE_RECORD_PENDING';
export const DELETE_RECORD_SUCCESS = 'DELETE_RECORD_SUCCESS';
export const DELETE_RECORD_FAILED = 'DELETE_RECORD_FAILED';