export const ADD_MEAL_PENDING = 'ADD_MEAL_PENDING';
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS';
export const ADD_MEAL_FAILED = 'ADD_MEAL_FAILED';

export const GET_MEALS_FROM_USER_PENDING = 'GET_MEALS_FROM_USER_PENDING';
export const GET_MEALS_FROM_USER_SUCCESS = 'GET_MEALS_FROM_USER_SUCCESS';
export const GET_MEALS_FROM_USER_FAILED = 'GET_MEALS_FROM_USER_FAILED';

export const DELETE_MEAL_PENDING = 'DELETE_MEAL_PENDING';
export const DELETE_MEAL_SUCCESS = 'DELETE_MEAL_SUCCESS';
export const DELETE_MEAL_FAILED = 'DELETE_MEAL_FAILED';