export const ADD_MEAL_PENDING = 'ADD_MEAL_PENDING';
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS';
export const ADD_MEAL_FAILED = 'ADD_MEAL_FAILED';

export const GET_MEALS_FROM_USER_PENDING = 'GET_MEALS_FROM_USER_PENDING';
export const GET_MEALS_FROM_USER_SUCCESS = 'GET_MEALS_FROM_USER_SUCCESS';
export const GET_MEALS_FROM_USER_FAILED = 'GET_MEALS_FROM_USER_FAILED';

export const DELETE_MEAL_PENDING = 'DELETE_MEAL_PENDING';
export const DELETE_MEAL_SUCCESS = 'DELETE_MEAL_SUCCESS';
export const DELETE_MEAL_FAILED = 'DELETE_MEAL_FAILED';

export const ADD_FOOD_TO_CURRENT_MEAL = 'ADD_FOOD_TO_CURRENT_MEAL';
export const REMOVE_FOOD_FROM_CURRENT_MEAL = 'REMOVE_FOOD_FROM_CURRENT_MEAL';
export const RESET_CURRENT_MEAL = 'RESET_CURRENT_MEAL';

export const UPDATE_CURRENT_MEAL_IN_STATE = 'UPDATE_CURRENT_MEAL_IN_STATE';

export const CHANGE_CURRENT_MEAL_NAME_AND_DATE_EATEN = 'CHANGE_CURRENT_MEAL_NAME_AND_DATE_EATEN'

export const UPDATE_CURRENT_MEAL_PENDING = 'UPDATE_CURRENT_MEAL_PENDING';
export const UPDATE_CURRENT_MEAL_SUCCESS = 'UPDATE_CURRENT_MEAL_SUCCESS';
export const UPDATE_CURRENT_MEAL_FAILED = 'UPDATE_CURRENT_MEAL_FAILED';

export const GET_MEALS_BY_PERIOD_PENDING = 'GET_MEALS_BY_PERIOD_PENDING';
export const GET_MEALS_BY_PERIOD_SUCCESS = 'GET_MEALS_BY_PERIOD_SUCCESS';
export const GET_MEALS_BY_PERIOD_FAILED = 'GET_MEALS_BY_PERIOD_FAILED';