export const ADD_OBJECTIVE_TO_CURRENT_GOAL = 'ADD_OBJECTIVE_TO_CURRENT_GOAL';
export const REMOVE_OBJECTIVE_FROM_CURRENT_GOAL = 'REMOVE_OBJECTIVE_FROM_CURRENT_GOAL';
export const CHANGE_CURRENT_GOAL_NAME_TOTAL_CALORIES_AND_DATE_START = 'CHANGE_CURRENT_GOAL_NAME_TOTAL_CALORIES_AND_DATE_START';
export const RESET_CURRENT_GOAL = 'RESET_CURRENT_GOAL';

export const ADD_GOAL_PENDING = 'ADD_GOAL_PENDING';
export const ADD_GOAL_SUCCESS = 'ADD_GOAL_SUCCESS';
export const ADD_GOAL_FAILED = 'ADD_GOAL_FAILED';

export const GET_GOALS_FROM_USER_PENDING = 'GET_GOALS_FROM_USER_PENDING';
export const GET_GOALS_FROM_USER_SUCCESS = 'GET_GOALS_FROM_USER_SUCCESS';
export const GET_GOALS_FROM_USER_FAILED = 'GET_GOALS_FROM_USER_FAILED';

export const DELETE_GOAL_PENDING = 'DELETE_GOAL_PENDING';
export const DELETE_GOAL_SUCCESS = 'DELETE_GOAL_SUCCESS';
export const DELETE_GOAL_FAILED = 'DELETE_GOAL_FAILED';