export const GET_ALL_FOODS_PENDING = 'GET_ALL_FOODS_PENDING';
export const GET_ALL_FOODS_SUCCESS = 'GET_ALL_FOODS_SUCCESS';
export const GET_ALL_FOODS_FAILED = 'GET_ALL_FOODS_FAILED';

export const ADD_CUSTOM_FOOD_PENDING = 'ADD_CUSTOM_FOOD_PENDING';
export const ADD_CUSTOM_FOOD_SUCCESS = 'ADD_CUSTOM_FOOD_SUCCESS';
export const ADD_CUSTOM_FOOD_FAILED = 'ADD_CUSTOM_FOOD_FAILED';

export const EDIT_CUSTOM_FOOD_PENDING = 'EDIT_CUSTOM_FOOD_PENDING';
export const EDIT_CUSTOM_FOOD_SUCCESS = 'EDIT_CUSTOM_FOOD_SUCCESS';
export const EDIT_CUSTOM_FOOD_FAILED = 'EDIT_CUSTOM_FOOD_FAILED';

export const DELETE_CUSTOM_FOOD_PENDING = 'DELETE_CUSTOM_FOOD_PENDING';
export const DELETE_CUSTOM_FOOD_SUCCESS = 'DELETE_CUSTOM_FOOD_SUCCESS';
export const DELETE_CUSTOM_FOOD_FAILED = 'DELETE_CUSTOM_FOOD_FAILED';

export const GET_FOOD_CATEGORIES_PENDING = 'GET_FOOD_CATEGORIES_PENDING';
export const GET_FOOD_CATEGORIES_SUCCESS = 'GET_FOOD_CATEGORIES_SUCCESS';
export const GET_FOOD_CATEGORIES_FAILED = 'GET_FOOD_CATEGORIES_FAILED';

export const CREATE_FOOD_CATEGORY_PENDING = 'CREATE_FOOD_CATEGORY_PENDING';
export const CREATE_FOOD_CATEGORY_SUCCESS = 'CREATE_FOOD_CATEGORY_SUCCESS';
export const CREATE_FOOD_CATEGORY_FAILED = 'CREATE_FOOD_CATEGORY_FAILED';

export const EDIT_FOOD_CATEGORY_PENDING = 'EDIT_FOOD_CATEGORY_PENDING';
export const EDIT_FOOD_CATEGORY_SUCCESS = 'EDIT_FOOD_CATEGORY_SUCCESS';
export const EDIT_FOOD_CATEGORY_FAILED = 'EDIT_FOOD_CATEGORY_FAILED';

export const DELETE_FOOD_CATEGORY_PENDING = 'DELETE_FOOD_CATEGORY_PENDING';
export const DELETE_FOOD_CATEGORY_SUCCESS = 'DELETE_FOOD_CATEGORY_SUCCESS';
export const DELETE_FOOD_CATEGORY_FAILED = 'DELETE_FOOD_CATEGORY_FAILED';