name: Build and Deploy a React App
on:
  push: #evento push
    branches: # en la rama MAIN
      - 'main'
jobs: # Si se hace el push, se hace el trabajo BUILD AND DEPLOY
  build-and-deploy:
    runs-on: ubuntu-latest #se va a hacer en una MV en GITHUB
    steps: #vamos hacer los siguientes pasos
      - name: Checkout ##=> verificar repositorio
        uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Install and Build ##=> instalar archivos y dependencias
        run:
          | # nota: la MV de GITHUB viene con REACT no es necesario instalarlo.
          npm install
          npm run build
      - name: Deploy ##=> realizar un deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5 # crea una rama llamada github pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          branch: main
          folder: build
